#ifndef __EPD_DATA_STRUCT_H__
#define __EPD_DATA_STRUCT_H__
#include "mini_fs_conf.h"

#pragma pack(1)


//屏幕厂商
typedef enum
{
  FIRM_NONE=0,
  FIRM_HOLITECH,
  FIRM_DKE,
  FIRM_WEIFENG,
}SCREEN_COMPANY_T;


//屏幕类型
typedef enum
{
  TYPE_NONE=0,
  LATTICE_EPD,
  SEGMENT_EPD,
  SEGMENT_LCD,
}SCREEN_SPECIES_T;

//合力泰IC
typedef enum
{
  LATTICE_HLTIC_NONE=0,
  LATTICE_HLTIC_SOLOMON_1608,
  LATTICE_HLTIC_SOLOMON_1673,
  LATTICE_HLTIC_SOLOMON_1675A,
  LATTICE_HLTIC_SOLOMON_1619,
  LATTICE_HLTIC_ULTRACHIP_8159,
}IC_LATTICE_HOLITECH_T;

//大连科脉IC
typedef enum
{
  LATTICE_DKEIC_SOLOMON_NONE=0,
  LATTICE_DKEIC_SOLOMON_1608,
  LATTICE_DKEIC_SOLOMON_1673,
  LATTICE_DKEIC_SOLOMON_1675A,
  LATTICE_DKEIC_SOLOMON_1619,
  LATTICE_DKEIC_ULTRACHIP_8159,
}IC_LATTICE_DKE_T;

//无锡威锋IC
typedef enum
{
  LATTICE_WFIC_ULTRACHIP_NONE=0,
  LATTICE_WFIC_ULTRACHIP_1608,
  LATTICE_WFIC_ULTRACHIP_1673,
  LATTICE_WFIC_ULTRACHIP_8151D,
  LATTICE_WFIC_ULTRACHIP_8154,
  LATTICE_WFIC_ULTRACHIP_8157,
  LATTICE_WFIC_ULTRACHIP_8159,
  LATTICE_WFIC_ULTRACHIP_8176,
}IC_LATTICE_ULTRACHIP_T;


//点阵edp屏幕尺寸
typedef enum
{
  LATTICE_EPD_NONE=0,
  LATTICE_SREN_152_152,
  LATTICE_SREN_200_200,
  LATTICE_SREN_250_122,
  LATTICE_SREN_212_104,
  LATTICE_SREN_296_152,
  LATTICE_SREN_296_128,
  LATTICE_SREN_300_400,
  LATTICE_SREN_448_600,
  LATTICE_SREN_384_640,
}SCREEN_SIZE_LT;


//断码edp屏幕尺寸
typedef enum
{
  SEGMENT_SEGMENT_EPD_NONE=0,
  SEGMENT_SREN_775_108,
  SEGMENT_SREN_775_121,
}SCREEN_SIZE_ST;
//断码edp合力泰ic
typedef enum
{
  SEGMENT_IC_SOLOMON_NONE=0,
  SEGMENT_IC_SOLOMON_1627,
}SEGMENT_IC_SOLOMON_T;

//LCD屏幕尺寸
typedef enum
{
  SEGMENT_LCD_NONE=0,
  LCD_SREN_154_159,
  LCD_SREN_213_159,
}SCREEN_SIZE_SLT;

//屏幕颜色
typedef enum
{
  COLOR_NONE=0,
  BLACK_WHITE,
  BLACK_WHITE_RED,
  BLACK_WHITE_YELLOW,
}SCREEN_COLOR_T;

//屏幕温度类型
typedef enum
{
  TEMPERATURE_NONE= 0,
  NORMAL_TMP,
  FREEZE_TMP,
}SCREEN_TEMPERATURE_T;

//屏幕方向
typedef enum
{
    SCREEN_DIRECTION_0 = 0,
    SCREEN_DIRECTION_90,
    SCREEN_DIRECTION_180,
    SCREEN_DIRECTION_270,
}SCREEN_DEF_DIRECTION_T;

//屏幕说明
typedef struct SCREEN_ATTR_T
{
  //SCREEN_COLOR_T      src_color;
  SCREEN_COMPANY_T    src_company;
  SCREEN_SPECIES_T    src_specties;
  //SCREEN_SIZE_LT      src_size;
}LATTICE_SCREEN_ATTR_T;

typedef struct SCREEN_DIS_T
{
  UINT16 screen_size;
  UINT16 h; 
  UINT16 w;
  UINT16 src_into;
  SCREEN_SIZE_LT      src_size;
  SCREEN_TEMPERATURE_T src_tmp;
  SCREEN_COLOR_T      src_color;
  SCREEN_DEF_DIRECTION_T  scr_direction;
  UINT8 ic_enum;
  bool refresh_screen_flag;
  file_id_t fd;
  UINT16 offset_1;
  file_id_t fd_red;
  UINT16 offset_2;
}SCREEN_DIS_T;


#pragma pack()
#endif
